DROP TABLE IF EXISTS INVOICE;

CREATE TABLE INVOICE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255),
    AMOUNT DOUBLE,
    INVOICE_DATE DATE,
    PAID BOOLEAN,
    STATUS VARCHAR(50)
);
